dist: focal  # Use Ubuntu 20.04, which supports GLIBC 2.27 or higher
language: node_js

node_js:
  - "lts/*"  # Use the latest LTS version of Node.js

# Ensure permissions for mocha binary before running tests
before_script:
  - chmod +x node_modules/.bin/mocha

# Install dependencies
install:
  - npm install  

# Run tests
script:
  - npm test -- --verbose

# Notifications for build status
notifications:
  email:
    recipients:
      - rohan.aryan2001@gmail.com
    on_success: always  # Send email only on success
    on_failure: always  # Send email on failure
