dist: focal  # Use Ubuntu 20.04 (supports GLIBC 2.27 or higher)
language: node_js

node_js:
  - "lts/*"

# Install dependencies
install:
  - npm install  

# Run tests
script:
  - npm test -- --verbose

# Notifications for build status
notifications:
  email:
    recipients:
      - rohan.aryan2001@gmail.com
    on_success: always  # Send email only on failure
    on_failure: always
